#!/usr/bin/env python3
"""
Generate markdown documentation pages for the pkanban CLI.

Pages are generated by introspecting the actual typer app in pkanban/cli.py,
so the docs cannot drift out of sync with the commands. Add a command to the
CLI, re-run this script, and the docs follow.

Usage:
    python scripts/generate_cli_docs.py [--output-dir PATH] [--check]
"""

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT))

import typer  # noqa: E402

from pkanban.cli import app  # noqa: E402

OUTPUT_DIR = REPO_ROOT / "docs" / "commands"
INDEX_PATH = REPO_ROOT / "docs" / "commands.md"

# Human-readable section titles for the index, keyed by top-level command name.
GROUP_TITLES = {
    "config": "Authentication & Configuration",
    "login": "Authentication & Configuration",
    "logout": "Authentication & Configuration",
    "apikey": "Authentication & Configuration",
    "board": "Board Management",
    "share": "Board Management",
    "column": "Column Management",
    "card": "Card Management",
    "org": "Organization Management",
    "team": "Team Management",
}

SECTION_ORDER = [
    "Authentication & Configuration",
    "Board Management",
    "Column Management",
    "Card Management",
    "Organization Management",
    "Team Management",
]


def is_group(command) -> bool:
    """True if the click/typer command has subcommands.

    Typer vendors its own click shim, so ``isinstance(cmd, click.Group)`` is
    unreliable across versions. Duck-typing on ``.commands`` is not.
    """
    return hasattr(command, "commands") and bool(getattr(command, "commands"))


def describe(command) -> str:
    """First line of a command's help text."""
    text = command.help or getattr(command, "short_help", None) or ""
    return text.strip().splitlines()[0] if text.strip() else ""


def split_params(command):
    """Split a command's params into (arguments, options)."""
    arguments, options = [], []
    for param in command.params:
        if param.name == "help":
            continue
        if type(param).__name__.endswith("Argument"):
            arguments.append(param)
        else:
            options.append(param)
    return arguments, options


# click's ParamType.name is not stable across versions: typer 0.15 reports
# "text"/"integer"/"boolean" where 0.27 reports "str"/"int"/"bool". Reading it
# raw meant a contributor on a different typer regenerated all 11 pages with
# spurious type churn, then failed the `--check` step in CI having changed
# nothing real. Normalising here makes the output depend on the CLI, not on
# whichever library version happens to be installed.
TYPE_NAMES = {
    "text": "str",
    "string": "str",
    "str": "str",
    "integer": "int",
    "int": "int",
    "boolean": "bool",
    "bool": "bool",
    "float": "float",
    "number": "float",
}


def type_name(param) -> str:
    """Stable label for a parameter's type."""
    raw = (getattr(param.type, "name", "") or "").lower()
    return TYPE_NAMES.get(raw, raw)


def is_bool(param) -> bool:
    """True for flag-style parameters, which take no value in usage."""
    return type_name(param) == "bool"


def usage_line(path: str, command) -> str:
    """Build the `pkanban ...` usage string for a command."""
    arguments, options = split_params(command)
    parts = [f"pkanban {path}"]

    for param in arguments:
        parts.append(f"<{param.name}>" if param.required else f"[{param.name}]")

    for param in options:
        flag = param.opts[0]
        if is_bool(param):
            parts.append(flag if param.required else f"[{flag}]")
        else:
            value = param.name.upper()
            parts.append(f"{flag} {value}" if param.required else f"[{flag} {value}]")

    return " ".join(parts)


def param_lines(command) -> list:
    """Markdown bullet lists describing a command's arguments and options."""
    arguments, options = split_params(command)
    lines = []

    if arguments:
        lines.extend(["**Arguments**", ""])
        for param in arguments:
            suffix = "" if param.required else " _(optional)_"
            help_text = f" — {param.help}" if param.help else ""
            lines.append(f"- `{param.name}` ({type_name(param)}){suffix}{help_text}")
        lines.append("")

    if options:
        lines.extend(["**Options**", ""])
        for param in options:
            flags = ", ".join(f"`{opt}`" for opt in param.opts)
            notes = []
            if param.required:
                notes.append("required")
            elif param.default is not None and not is_bool(param):
                notes.append(f"default: `{param.default}`")
            note_text = f" _({', '.join(notes)})_" if notes else ""
            help_text = f" — {param.help}" if param.help else ""
            lines.append(f"- {flags} ({type_name(param)}){note_text}{help_text}")
        lines.append("")

    return lines


def render_command(path: str, command, heading: str) -> list:
    """Render one leaf command as markdown lines."""
    lines = [f"{heading} `pkanban {path}`", ""]

    description = describe(command)
    if description:
        lines.extend([description, ""])

    lines.extend(["```bash", usage_line(path, command), "```", ""])
    lines.extend(param_lines(command))
    return lines


def anchor(text: str) -> str:
    """Slug for a heading anchor.

    Must stay in sync with the ``slugify`` helper in
    ``frontend/src/routes/Docs.svelte``, which stamps these ids onto rendered
    headings. Lowercase, drop backticks and punctuation, collapse whitespace
    runs to a single hyphen.
    """
    slug = text.lower().replace("`", "")
    slug = "".join(c if (c.isalnum() and c.isascii()) or c in " -" else "" for c in slug)
    return "-".join(slug.split())


def render_page(name: str, command) -> str:
    """Render a full page for a top-level command (group or single command)."""
    lines = [f"# pkanban {name}", ""]

    description = describe(command)
    if description:
        lines.extend([description, ""])

    if not is_group(command):
        lines.extend(["```bash", usage_line(name, command), "```", ""])
        lines.extend(param_lines(command))
    else:
        subcommands = sorted(command.commands.items())

        lines.extend(["## Commands", ""])
        for sub_name, sub in subcommands:
            path = f"{name} {sub_name}"
            summary = describe(sub)
            link = f"#pkanban-{anchor(path)}"
            lines.append(
                f"- [`pkanban {path}`]({link})" + (f" — {summary}" if summary else "")
            )
        lines.extend(["", "---", ""])

        for sub_name, sub in subcommands:
            lines.extend(render_command(f"{name} {sub_name}", sub, "##"))

    lines.extend(["## See Also", "", "- [All Commands](/docs/commands)", "- [CLI Reference](/docs/reference)", ""])
    return "\n".join(lines)


def render_index(top_level: dict) -> str:
    """Render the docs/commands.md index page."""
    sections = {title: [] for title in SECTION_ORDER}

    for name, command in sorted(top_level.items()):
        title = GROUP_TITLES.get(name, "Board Management")
        sections[title].append((name, command))

    lines = [
        "# pkanban Commands",
        "",
        "Complete reference for all pkanban commands.",
        "",
        "## Contents",
        "",
    ]

    for title in SECTION_ORDER:
        if sections[title]:
            lines.append(f"- [{title}](#{anchor(title)})")

    lines.extend(["", "---", ""])

    for title in SECTION_ORDER:
        if not sections[title]:
            continue
        lines.extend([f"## {title}", ""])
        for name, command in sections[title]:
            summary = describe(command)
            lines.append(f"### [`pkanban {name}`](/docs/commands/{name})")
            lines.append("")
            if summary:
                lines.extend([summary, ""])
            if is_group(command):
                for sub_name, sub in sorted(command.commands.items()):
                    sub_summary = describe(sub)
                    lines.append(
                        f"- `pkanban {name} {sub_name}`"
                        + (f" — {sub_summary}" if sub_summary else "")
                    )
                lines.append("")

    lines.extend(
        [
            "---",
            "",
            "## Quick Links",
            "",
            "- [Quick Start Guide](/docs/quickstart)",
            "- [Common Workflows](/docs/workflows)",
            "- [Full Reference](/docs/reference)",
            "",
        ]
    )

    return "\n".join(lines)


def build_pages() -> dict:
    """Return {relative_path: content} for every page this generator owns."""
    root = typer.main.get_command(app)
    top_level = {
        name: command
        for name, command in root.commands.items()
        if not getattr(command, "hidden", False)
    }

    pages = {
        Path("docs") / "commands" / f"{name}.md": render_page(name, command)
        for name, command in top_level.items()
    }
    pages[Path("docs") / "commands.md"] = render_index(top_level)
    return pages


def main():
    parser = argparse.ArgumentParser(
        description="Generate CLI docs by introspecting the typer app"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=OUTPUT_DIR,
        help="Directory for per-command pages (default: docs/commands)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the docs on disk are out of date",
    )
    args = parser.parse_args()

    pages = build_pages()

    if args.check:
        stale = [
            path
            for path, content in pages.items()
            if not (REPO_ROOT / path).exists()
            or (REPO_ROOT / path).read_text(encoding="utf-8") != content
        ]
        if stale:
            print("CLI docs are out of date. Run: python scripts/generate_cli_docs.py")
            for path in stale:
                print(f"  stale: {path.as_posix()}")
            return 1
        print(f"CLI docs are up to date ({len(pages)} files).")
        return 0

    args.output_dir.mkdir(parents=True, exist_ok=True)
    for path, content in pages.items():
        target = REPO_ROOT / path
        target.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n" so output is identical on Windows and Linux, keeping
        # --check honest regardless of the committer's core.autocrlf setting.
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        print(f"  wrote: {path.as_posix()}")

    print(f"\nGenerated {len(pages)} markdown files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
